#!/bin/bash

DOCKER_INTERNAL_IP=`docker inspect -f '{{ .NetworkSettings.IPAddress }}' sshpanel-softether`

docker exec sshpanel-softether vpncmd $DOCKER_INTERNAL_IP:5555  /SERVER /PASSWORD:$SOFTETHER_ADMIN_PASSWORD /CSV /CMD: ServerCertGet server.crt

SERVER_CA=`docker exec sshpanel-softether cat server.crt`

echo "SERVER CA"
echo $SERVER_CA
